
name: publish_artifacts_to_aptly
on: 
  workflow_call:
    inputs:
      artifact-name:
        required: false
        type: string
        default: ''
      repo-name:
        required: true
        type: string
jobs:
  process-artifacts:
    runs-on: [self-hosted, lightsail]
    name: Process all artifacts
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{inputs.artifact-name}}
          path: ${{runnter.temp}/artifacts
      - name: Display structure of downloaded files
        run: ls -R
      - name: Upload to aptly
        run: find $RUNNER_TEMP/artifacts/ -name "*.deb" | xargs -I {} -d '\n' curl --user ${{secrets.APTLY_API_USER}}:${{secrets.APTLY_API_PASS}} -X POST -F 'file=@"{}"' https://aptly.allstarlink.org/api/files/${{inputs.repo-name}}-incoming
      
